/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pipes;

import java.awt.Color;

/**
 *
 * @author Ross
 */
public class LbendGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public LbendGUI() {
        initComponents();
        textArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSize = new javax.swing.JLabel();
        tFSize = new javax.swing.JTextField();
        lWeight = new javax.swing.JLabel();
        tFWeight = new javax.swing.JTextField();
        lShortLeg = new javax.swing.JLabel();
        tFShortLeg = new javax.swing.JTextField();
        lLongLeg = new javax.swing.JLabel();
        tFLongLeg = new javax.swing.JTextField();
        butGetCurve = new javax.swing.JButton();
        lShapeFactor = new javax.swing.JLabel();
        tFShapeFactor = new javax.swing.JTextField();
        lMaterial = new javax.swing.JLabel();
        cBMaterial = new javax.swing.JComboBox();
        lService = new javax.swing.JLabel();
        cBService = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tFMaxTemp = new javax.swing.JTextField();
        lMinTemp = new javax.swing.JLabel();
        tFMinTemp = new javax.swing.JTextField();
        butBack = new javax.swing.JButton();
        butCalculate = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        butClear = new javax.swing.JButton();
        butPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tFID = new javax.swing.JTextField();
        butClearTA = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(35, 0), new java.awt.Dimension(35, 0), new java.awt.Dimension(35, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("L-Bend");

        lSize.setText("Pipe size (inches)");

        lWeight.setText("Pipe weight (sch.)");

        lShortLeg.setText("Length of short leg (mm)");

        lLongLeg.setText("Length of long leg (mm)");

        butGetCurve.setText("Get curve to read at");
        butGetCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGetCurveActionPerformed(evt);
            }
        });

        lShapeFactor.setText("Shape factor");

        lMaterial.setText("Pipe material");

        cBMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Carbon steel grade A", "Carbon steel grade B", "Carbon Moly", "Low Chrome Moly", "Annealed Nickel", "Annealed Monel", "Aluminum 3003-H112", "Aluminum 5154-H112", "Aluminum 6061-T6", "Medium Chrome Moly", "Austenitic Stainless" }));

        lService.setText("Service");

        cBService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Power", "Oil" }));

        jLabel1.setText("Maximum temperature (°C)");

        lMinTemp.setText("Minimum temperature (°C)");

        butBack.setText("Back to start");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        butCalculate.setText("Calculate");
        butCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalculateActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setToolTipText("");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        butClear.setText("Clear all");
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });

        butPrint.setText("Print");
        butPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrintActionPerformed(evt);
            }
        });

        jLabel2.setText("Pipe section ID");

        butClearTA.setText("Clear text area");
        butClearTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butClearTA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butClear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lWeight)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lLongLeg)
                                                .addGap(30, 30, 30)
                                                .addComponent(tFLongLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lShortLeg)
                                                    .addComponent(lSize)
                                                    .addComponent(jLabel2))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tFSize, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tFID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tFWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tFShortLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(24, 24, 24))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lService)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cBService, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lMaterial)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cBMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lShapeFactor)
                                                .addGap(84, 84, 84)
                                                .addComponent(tFShapeFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(lMinTemp))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tFMinTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tFMaxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(butCalculate))
                                            .addGap(19, 19, 19)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(butGetCurve)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lWeight)
                            .addComponent(tFWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lShortLeg)
                            .addComponent(tFShortLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFLongLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lLongLeg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butGetCurve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFShapeFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lShapeFactor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lMaterial))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lService)
                            .addComponent(cBService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFMaxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFMinTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMinTemp))
                        .addGap(18, 18, 18)
                        .addComponent(butCalculate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butClearTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butClear)
                        .addGap(16, 16, 16)
                        .addComponent(butPrint)
                        .addGap(18, 18, 18)
                        .addComponent(butBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGetCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGetCurveActionPerformed
        boolean lengths = false;//vaiable to check values are entered and correct
        boolean shortLong = false;
        String size = tFSize.getText();//For getting effective length
        String weight = tFWeight.getText();

        //check that size and weight have been entered
        if ((size.length() != 0) & (weight.length() != 0)) {
            lengths = true;
        }

        try {
            double shortLeg = Double.parseDouble(tFShortLeg.getText());//get parameters
            double longLeg = Double.parseDouble(tFLongLeg.getText());
            if (longLeg > shortLeg) {//check that LongLeg is greater than shortLeg
                shortLong = true;
            }

            if (shortLong & lengths) {//continue if values are entered and correct
                double readAt = driver.CurveAt(shortLeg, longLeg);//variable 

                textArea.append("Pipe section ID: " + tFID.getText() + "\n");
                textArea.append("Read the shape factor on Chart 3 at 0 and curve " + readAt + ".\n");
                textArea.append("Enter the shape factor into its text field.\n\n");

                //Get effective elbow diameter=======================================
                Fl = driver.DiameterLength(shortLeg, longLeg, 0, size, weight);
                //System.out.println("4");
                //===================================================================

            } else {
                if (lengths == false) {
                    driver.errorMessageNormal("Please enter the size and weight of the pipes.");
                } else {

                    driver.errorMessageNormal("Make sure that the length entered for the long leg is\n"
                            + "greater than the length entered for the short leg.");
                }
            }
        } catch (NumberFormatException nfe) {
            driver.errorMessageNormal("Please make sure that the values entered for the \n"
                    + "short leg and long leg are correct. Only digits, not any other characters,\n"
                    + " should be entered");
        } catch (Exception e) {
            driver.errorMessageNormal("From GetCurveActionPerformed: " + e);
        }
    }//GEN-LAST:event_butGetCurveActionPerformed

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        tFID.setText("");
        tFLongLeg.setText("");
        tFShortLeg.setText("");
        tFMaxTemp.setText("");
        tFMinTemp.setText("");
        tFShapeFactor.setText("");
        tFSize.setText("");
        tFWeight.setText("");
        textArea.setText("");
        cBMaterial.setSelectedIndex(0);
        cBService.setSelectedIndex(0);
        Color normal = new Color(236, 233, 216);
        panel.setBackground(normal);//clear all fields/colours before disposing of GUI

        this.dispose();
        gui.setVisible(true);
    }//GEN-LAST:event_butBackActionPerformed

    private void butCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalculateActionPerformed
        try {
            Fs = Double.parseDouble(tFShapeFactor.getText());//get shape factor from text Field.

            int matIndex = cBMaterial.getSelectedIndex();//get parameters
            int servIndex = cBService.getSelectedIndex();
            double hot = driver.CtoF(Double.parseDouble(tFMaxTemp.getText()));
            double cold = driver.CtoF(Double.parseDouble(tFMinTemp.getText()));
            boolean temp = false;//to check temperatures are correct

            if (hot > cold) {//check that hot is higher than cold
                temp = true;
            }

            //calculate if all parameters are int the correct format
            if ((matIndex != 0) & (servIndex != 0) & (Fs != 0) & (temp)) {
                //get service and material
                String material = driver.getSelectedMaterial(matIndex);
                String service = driver.GetService(servIndex);

                Fe = driver.ExpansionFactor(matIndex, hot, cold);
                Sa = driver.GetAllowableStress(matIndex, servIndex, hot);

                if (Sa == 0) {
                    driver.errorMessageNormal("Temperatures entered not valid for\n"
                            + "type of pipe selected");
                }

                Se = (Fe * Fs) / Fl;//do final calculation

                textArea.append("Maximum allowable stress:" + Sa + "\n");//inform user of results
                textArea.append("Computed Stress Range: " + Se + "\n\n");

                if (Se < Sa) {//determine colour depending on whether the system is safe or not
                    textArea.append("The actual range is LESS than the maximum allowable stress\n\n");
                    panel.setBackground(Color.green); //set panel to green
                } else {
                    textArea.append("The actual range is MORE than the maximum allowable stress\n\n");
                    panel.setBackground(Color.red);
                }
            } else {//inform user of incorrect values.
                if (Fs == 0) {
                    driver.errorMessageNormal("Please enter the shape factor. It may not be equal to 0.");
                } else {
                    if (temp == false) {
                        driver.errorMessageNormal("Please make sure that the maximum temperature is higher\n"
                                + " than the minimum temperature");
                    } else {
                        driver.errorMessageNormal("Please select the material and service");
                    }
                }
            }
        } catch (NumberFormatException nfe) {
            driver.errorMessageNormal("Please make sure that the values entered for the \n"
                    + "temperatures and shape factor are correct. Only digits, not any other characters,\n"
                    + " should be entered");
        } catch (Exception e) {
            driver.errorMessageNormal("From CalculateActionPerformed: " + e);
        }

    }//GEN-LAST:event_butCalculateActionPerformed

    private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
        tFID.setText("");
        tFLongLeg.setText("");
        tFShortLeg.setText("");
        tFMaxTemp.setText("");
        tFMinTemp.setText("");
        tFShapeFactor.setText("");
        tFSize.setText("");
        tFWeight.setText("");
        textArea.setText("");
        cBMaterial.setSelectedIndex(0);
        cBService.setSelectedIndex(0);
        panel.setBackground(driver.colour("default"));
    }//GEN-LAST:event_butClearActionPerformed

    private void butPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrintActionPerformed
        String[] ar = new String[11];//declare array and numberof elements
        int nrE = 0;

        if (cBMaterial.getSelectedIndex() != 0 & cBService.getSelectedIndex() != 0) {
            //fill array
            ar[nrE] = "ID: " + tFID.getText();
            nrE++;//=1
            ar[nrE] = "Size: " + tFSize.getText();
            nrE++;
            ar[nrE] = "Schedule: " + tFWeight.getText();
            nrE++;
            ar[nrE] = "Short leg (mm): " + tFShortLeg.getText();
            nrE++;
            ar[nrE] = "Long leg (mm): " + tFLongLeg.getText();
            nrE++;
            ar[nrE] = "Material: " + driver.getSelectedMaterial(cBMaterial.getSelectedIndex());
            nrE++;
            ar[nrE] = "Service: " + driver.GetService(cBService.getSelectedIndex());
            nrE++;
            ar[nrE] = "Maximum temperature (°C): " + tFMaxTemp.getText();
            nrE++;
            ar[nrE] = "Minimum temperature (°C): " + tFMinTemp.getText();
            nrE++;// nrE = 9

            ar[nrE] = "Maximum allowable stress: " + Sa;// global variable
            nrE++;

            ar[nrE] = "Computed Stress Range: " + Se;//global variable
            nrE++;// = 11

            Print_Something ps = new Print_Something(ar);

        } else {
            driver.infoMessageNormal("Please make sure that both service and material are selected.");
        }
    }//GEN-LAST:event_butPrintActionPerformed

    private void butClearTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearTAActionPerformed
        textArea.setText("");
        panel.setBackground(driver.colour("default"));
    }//GEN-LAST:event_butClearTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LbendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LbendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LbendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LbendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LbendGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBack;
    private javax.swing.JButton butCalculate;
    private javax.swing.JButton butClear;
    private javax.swing.JButton butClearTA;
    private javax.swing.JButton butGetCurve;
    private javax.swing.JButton butPrint;
    private javax.swing.JComboBox cBMaterial;
    private javax.swing.JComboBox cBService;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lLongLeg;
    private javax.swing.JLabel lMaterial;
    private javax.swing.JLabel lMinTemp;
    private javax.swing.JLabel lService;
    private javax.swing.JLabel lShapeFactor;
    private javax.swing.JLabel lShortLeg;
    private javax.swing.JLabel lSize;
    private javax.swing.JLabel lWeight;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tFID;
    private javax.swing.JTextField tFLongLeg;
    private javax.swing.JTextField tFMaxTemp;
    private javax.swing.JTextField tFMinTemp;
    private javax.swing.JTextField tFShapeFactor;
    private javax.swing.JTextField tFShortLeg;
    private javax.swing.JTextField tFSize;
    private javax.swing.JTextField tFWeight;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    Driver driver = new Driver();
    FirstGUI gui = new FirstGUI();
    double Fs = 0;//variables for final clculation
    double Fl = 0;
    double Fe = 0;
    double Sa = 0;
    double Se = 0;
}
